#!/bin/sh

source ./.env
IMAGE="${COMPOSE_PROJECT_NAME}_app"

docker build . -t "$IMAGE"
docker save "$IMAGE" | gzip | pv | ssh "$1" "zcat | docker load"
APP_URL="$APP_URL" docker-compose -H "ssh://$1" up -d
