version: '3'

volumes:
  storage:
  db:

services:
  app:
    build: .
    restart: on-failure:3
    ports:
      - 8000:80
    volumes:
      - storage:/var/www/html/storage
      - ./app:/var/www/html/app
      - ./public:/var/www/html/public
    environment:
      APP_URL: '${APP_URL}'
    depends_on:
      - db
  db:
    image: mariadb
    restart: on-failure:3
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
